Day-6
madhusdhnn/coding-samples-java pull request #9
Opened 2023-08-09 19:37 UTC by madhusdhnn

2023-08-12 13:26 UTC, venkatyuva requested changes

2023-08-12 13:26 UTC, venkatyuva commented on src/main/java/org/example/list/SinglyLinkedList.java
> +            if (list1.next == null) {
Why are we doing this here?

2023-08-12 13:26 UTC, venkatyuva commented on src/main/java/org/example/list/SinglyLinkedList.java
> +    public void partition(int pivot) {
Is this code working for all the test cases in gfg/leetcode?

2023-08-14 06:16 UTC, madhusdhnn commented on src/main/java/org/example/list/SinglyLinkedList.java
> +    public void partition(int pivot) {
Yes

2023-08-14 06:18 UTC, madhusdhnn commented on src/main/java/org/example/list/SinglyLinkedList.java
> +            if (list1.next == null) {
Customization of `tail` node in this code. It is not required in the actual submission code

2023-09-05 11:58 UTC, merged